// <auto-generated />
namespace Intens_Zadatak.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NavigationalProps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NavigationalProps));
        
        string IMigrationMetadata.Id
        {
            get { return "202111091436466_NavigationalProps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
